### ISSUE TITLE
Remove flags (s2a_timeout, s2a_enable_appengine_dialer)

### ISSUE THREAD

**Issue by howardjohn** [google/s2a-go#107]
These flags are registered by any binary that imports this library as they are registered in init(). This in turn means they should up in our binaries. This is unexpected for users.

While I couldn't find anything official recommending not to do that, looking at our entire dependency tree, which is quite large, this is the only library that does this. This leads me to believe that using flags in libraries (as opposed to binaries) is not a very established pattern in the ecosystem.

**Comment by xmenxk** [comment]
updating google-api-go-client dependency in https://github.com/googleapis/google-api-go-client/pull/1989
